# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edge_communication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'edge_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65\x64ge_communication.proto\x12\x04\x65\x64ge\"\x8d\x01\n\x10VideoFeatureData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x11\n\tcamera_id\x18\x03 \x01(\x05\x12\x13\n\x0b\x66\x65\x61ture_map\x18\x04 \x01(\x0c\x12\x12\n\nvoxel_data\x18\x05 \x01(\x0c\x12\x18\n\x10\x63ompressed_image\x18\x06 \x01(\x0c\"7\n\rOnvifMetadata\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\t\"\x9f\x01\n\x11\x45\x64geStreamRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12,\n\nvideo_data\x18\x02 \x01(\x0b\x32\x16.edge.VideoFeatureDataH\x00\x12)\n\nonvif_data\x18\x03 \x01(\x0b\x32\x13.edge.OnvifMetadataH\x00\x12\x13\n\theartbeat\x18\x04 \x01(\tH\x00\x42\t\n\x07payload\"<\n\x15ServerControlResponse\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x12\n\nparameters\x18\x02 \x01(\t2a\n\x0b\x45\x64geManager\x12R\n\x14StreamDataAndControl\x12\x17.edge.EdgeStreamRequest\x1a\x1b.edge.ServerControlResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFEATUREDATA']._serialized_start=35
  _globals['_VIDEOFEATUREDATA']._serialized_end=176
  _globals['_ONVIFMETADATA']._serialized_start=178
  _globals['_ONVIFMETADATA']._serialized_end=233
  _globals['_EDGESTREAMREQUEST']._serialized_start=236
  _globals['_EDGESTREAMREQUEST']._serialized_end=395
  _globals['_SERVERCONTROLRESPONSE']._serialized_start=397
  _globals['_SERVERCONTROLRESPONSE']._serialized_end=457
  _globals['_EDGEMANAGER']._serialized_start=459
  _globals['_EDGEMANAGER']._serialized_end=556
# @@protoc_insertion_point(module_scope)
