events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    upstream foxglove {
        server foxglove_bridge:8765;
    }

    # API & WebSocket Traffic
    server {
        listen 8080;
        server_name _;

        # Foxglove WebSocket Bridge 연결
        location / {
            proxy_pass http://foxglove;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 86400;
        }
    }
}
