# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.protos.edge_communication_pb2 as edge__communication__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in edge_communication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdgeManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamDataAndControl = channel.stream_stream(
                '/edge.EdgeManager/StreamDataAndControl',
                request_serializer=edge__communication__pb2.EdgeStreamRequest.SerializeToString,
                response_deserializer=edge__communication__pb2.ServerControlResponse.FromString,
                _registered_method=True)


class EdgeManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamDataAndControl(self, request_iterator, context):
        """양방향 스트리밍(Bi-directional Streaming):
        엣지은 영상 분석 중간 결과나 ONVIF 메타데이터를 전송하고,
        서버는 각 장치에 대한 카메라 제어 등의 명령을 전송합니다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamDataAndControl': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDataAndControl,
                    request_deserializer=edge__communication__pb2.EdgeStreamRequest.FromString,
                    response_serializer=edge__communication__pb2.ServerControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edge.EdgeManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edge.EdgeManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamDataAndControl(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/edge.EdgeManager/StreamDataAndControl',
            edge__communication__pb2.EdgeStreamRequest.SerializeToString,
            edge__communication__pb2.ServerControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
